### ISSUE TITLE
Unauthorized requests to GitHub API limited to 60 requests per hour

### ISSUE THREAD

**Issue by njjoos** [comunica/comunica-packager#2]
The current way of getting all the information about actors and mediators is through the GitHub API. These requests are unauthorized since the application is a client-side web app. Now the limit for unauthorized requests is only 60 requests per hour, not enough for making one config file.

Potential solution: create a custom API server that handles these requests in an authorized way

**Comment by njjoos** [comment]
Only one request via the GitHub API is sent during the first load of the web app (to retrieve all the packages their name). All subsequent requests are done via linkedsoftwaredependencies.org from now on.

**Comment by rubensworks** [comment]
Nice :-)
