### ISSUE TITLE
Make shareable URL

### ISSUE THREAD

**Issue by njjoos** [comunica/comunica-packager#24]
A shareable URL would contain the necessary information to share a configuration so that another user can work on it

**Comment by rubensworks** [comment]
Assuming the user does not modify a default config, this should be easy to do. (once the user starts modifying things, I would stop persisting in the URL)

For example, using a hash such as `#preset=comunica-sparql&set=sparql-query-operators`, the app could display the `sparql-query-operators` set of Comunica SPARQL.
