### ISSUE TITLE
How to load packages from other repos?

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica-packager#40]
Is it possible to somehow support the inclusion of modules from other repos, such as https://github.com/comunica/comunica-feature-amf/tree/master/packages?

If so, we should add this one by default.

It might also be good if we can somehow load a custom package by npm/github URL. (this will probably require some thinking)

**Comment by njjoos** [comment]
Resolved using the `packageUrls` field in the  `app-config.json` file
