### ISSUE TITLE
Light up related components

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica-packager#9]
When selecting an actor or mediator, all immediately connected actors and mediators should be lit up (e.g., a brighter color).

For example, when selecting actor A that makes use of mediator M, then mediator M should be visually lit up.

**Comment by njjoos** [comment]
This would be difficult if a used mediator is not in the same set as the selected actor

**Comment by rubensworks** [comment]
In that case, perhaps the set's button could light up?

**Comment by njjoos** [comment]
That's a possibility, also what is meant with "selecting an actor"? Is it simply opening one and if so would that mean to close all other actors?

**Comment by rubensworks** [comment]
> also what is meant with "selecting an actor"?

That's up for discussion :-)
Could be either clicking or hovering over one.
